# Copyright 2022 The SODA Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Check for Gelato source code existed
  stat:
    path: "{{ gelato_work_dir }}/installer/ansible"
  ignore_errors: yes
  register: gelatoexisted

- name: Uninstall Gelato using ansible playbook
  shell: "{{ item }}"
  with_items:
    - ansible-playbook clean.yml -i local.hosts | tee /var/log/gelato_ansible.log
  when:
    - gelatoexisted.stat.exists is defined or gelatoexisted.stat.exists == true
  ignore_errors: yes
  args:
    chdir: "{{ gelato_work_dir }}/installer/ansible"
